theme: minima
timezone: America/Sao_Paulo
encoding: utf-8
permalink: /:slug
show_excerpts: true
title: Jerônimo Fagundes da Silva
author: Jerônimo Fagundes da Silva
email: contato@jeronimo.dev.br
instagram_username: jeronimo.dev.br
github_username: jeronimofs
mastodon:
  - username: jeronimofagundes
    instance: bolha.us
minima:
  date_format: "%d/%m/%Y"